export const CART_MODULE = 'cart'

export const CART_ITEMS_KEY = 'selectedItems'

export const GET_CART_ITEMS = 'GET_CART_ITEMS'
export const GET_CART_TOTAL_COUNT = 'GET_CART_TOTAL_COUNT'

export const SET_CART_ITEMS = 'SET_CART_ITEMS'

export const ACTION_ADD_ITEM_TO_CART = 'ACTION_ADD_ITEM_TO_CART'
export const ACTION_REMOVE_ITEM_FROM_CART = 'ACTION_REMOVE_ITEM_FROM_CART'
export const ACTION_REMOVE_ALL_ITEMS = 'ACTION_REMOVE_ALL_ITEMS'